name: "CI: Lint (actions)"
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"
  push:
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
      - name: actionlint
        run: nix shell nixpkgs#actionlint --command actionlint
